FROM centos:centos8.4.2105

# [must] maintainer label
LABEL "maintainer"="edgesenseai"

# [must] timezone must be Asia/Shanghai (CST)
ENV TIME_ZONE=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone

# https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
RUN cd /etc/yum.repos.d/;sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN cd /etc/yum.repos.d/;sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN dnf -y install --allowerasing telnet tcpdump wget net-tools bind-utils && dnf -y clean all
RUN dnf -y install --allowerasing sysstat lsof lrzsz unzip && dnf -y clean all

RUN sed -i 's/^ssl/#ssl/g' /etc/yum.conf

VOLUME /app/log
VOLUME /app/conf

# [suggest] working dir is app
ADD . /app
WORKDIR /app

# [suggest] declare exposed port
EXPOSE 10001
ENV LD_LIBRARY_PATH lib:$LD_LIBRARY_PATH

# [suggest] use command array
ENTRYPOINT ["/bin/bash","-c"]
CMD ["bash start.sh"]

# docker build ./pack -t hub.docker.com/sea-palm-racer:v0.1 --file ./pack/Dockerfile_centos8
